### ISSUE TITLE
Display Data on grafana Spike

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#16]
EC2 t2.micro install grafana and import dynamodb data to grafana 

**(Spike)** how to link DynamoDB table to grafana?

Objective: Visualize dynamodb data in grafana

**Comment by XrosHeart05** [comment]
The issue is taken up and started

**Comment by XrosHeart05** [comment]
[NEED TO UPDATE]

Currently there is no direct connection from DynamoDB to Grafana; however, there are some options with which such a connection can be established by means of a "bridge". Next I will detail the valid options as of today (15/Jun/2023) that I have been able to find to establish such a connection:

1. AWS AppSync - GraphQL: 
I will start with what we believe is the best solution to this problem.
AWS AppSync allows the creation of an API on which you can make use of GraphQL and expose it through an endpoint, with this we can establish the connection with Grafana through the GraphQL Data Source plugin (Dependency with Grafana 7.0.0 or higher versions).
For this option I will detail the steps to follow:

> Mandatory and Dependent:

- Have an account in which you can make use of this AWS service.
- Have the necessary permissions for the API creation.
- Have a DynamoDB table defined (optionally with data).

> Only mandatory:

- Select Create an API
- Select the API type 'GraphQL APIs' and the option 'Import from DynamoDB'.
- Indicate the name of the API
- Select if the API will be private or not
- Select the region in which the table to be selected is located, for example in my case 'us-east-1'.
- Select the name of the table from which you want to perform the data extraction.
- Assign a role or create a new one
- Specify a GraphQL model to be used, this must be given a name.
- Click on the 'Create API' button.


> Notes about AWS AppSync:

AWS AppSync as of today (15/Jun/2023; this may change in the future) offers during the first year up to 450 000 monthly requests without charge (read more details about the prices in this [link](https://aws.amazon.com/appsync/pricing/?nc1=h_ls)); the costs may go up depending on the use of this; it is very important to take this detail into consideration as it depends on the budget of each person/entity this will suppose if it is a good option or not.

> Setup Schema

In AWS AppSync you'll need to setup the 'Schema' or 'Schemas' needed to expose the data (Is very important define the right data type of the "columns"; more info in [docs GraphQL](https://graphql.org/learn/schema/), because some graphs can only be displayed if data type in the right type, ex. height: 86.4; this must be 'Float' type instead 'String' type).

> DataSource Setup

A name related to the operations you are going to perform with this connection is recommended.
- In the 'HTTP' section
  - Set in the URL field all the URL including the graphql endpoint; this url or endpoint can be found in the API configuration section; API Details section, value of 'GraphQL endpoint'.
  - The default access is 'Server'; if you need another type of access it must be set at this point.
- In the 'Auth' section
  - Provide the required authentication data; if not required leave these values empty.
- In the Custom HTTP Headers section
  - You must validate if an API-Key exists in the GraphQL server; this can be found in 'AWS AppSync', in the API configuration section; section 'Default authorization mode', 'Configuration', 'API keys'; by default there must be a value, you must copy it and place it in the Grafana Data Source configuration under the Header 'x-api-key' and in the Value you must place the previously copied value.
- Finally, click on the 'Save & test' button; this should display a 'Success' message if the connection is correct; if this is not the case, validate in detail if you are missing a value or if it was entered incorrectly.

> Grafana Dashboard Setup -- UPDATE --

2. Rockset:
Using the Rockset tool, it is possible to establish a connection with Grafana; in the following [link](https://rockset.com/docs/grafana/) the steps to follow to establish this connection are detailed.

3. InfluxDB:
To make use of a connection through InfluxDB, an EC2 instance needs to be configured; once it is configured, its URL and connection port can be used to configure it in Grafana.
However, there is a problem and that is that you cannot use DynamoDB; you must pass the data to another table, for example with AWS Glue.
To transfer data from DynamoDB, a Job must be generated to perform this task (ETL).
Once you have the data in the other table, you can generate the connection in Grafana through InfluxDB.

**Comment by XrosHeart05** [comment]
Actually displaying data in Grafana
![imagen](https://github.com/tachOrg/Real-Time-Data-Processing-Application/assets/43551637/b5db8913-e6d0-40af-a8ad-2aaf2a44fb9b)

**Comment by tacho090** [comment]
data is displayed
