### ISSUE TITLE
Create CloudFormation template for pipeline

### ISSUE THREAD

**Issue by tacho090** [tachOrg/Real-Time-Data-Processing-Application#6]
Map the entire process from start to finish into a CloudFormation template.

**Comment by XrosHeart05** [comment]
Actually I'm trying to execute DynamoDB template parts to fix some errors returned in CF events log.
DynamoDB is needing permissions to execute/build the lambda funcion specified into the template.
I think that IAM permission must be needed in future stacks buildings.

**Comment by XrosHeart05** [comment]
The DynamoDB permission was granted into cloudformation, but now I'm needing this permission into DynamoDB too because the workflow of the template execution is been stopped by DynamoDB, the table into template is already created, so I tried to delete manually from DynamoDB interface but permissions denied me the action.
Roles and Policies sections were added at template, I need to test it more, and one need is get delete table permission

**Comment by XrosHeart05** [comment]
With CloudFormation DynamoDB permission the delete of table into events process was sucessful, then the lambda function role arn was updated, because the previous arn pointed to ghost/non-existing arn.
The lambda function need a trigger, this was supplied by AWS::Lambda::EventSourceMapping

**Comment by tacho090** [comment]
This issue was completed on Apr 13
